# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Marc Fabián Vilà
title: Videogame Programmer
email: marcfv97@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: ImMarkuss
github_username:  xDragan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: markussfabi
linkedin_username: linkedin.com/in/marc-fabián-i-vilà-855615108
# pinterest_username: jekyll
youtube_username: 3009markuss
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Marc and I'm a videogame developer interested in programming (C/C#/C++) and design. I'm open to keep learning and improving as a developer and work on new projects in the years to come.

  I am most skilled in: <mark>Programming</mark> and <mark>Designing</mark> videogames.
  
  I have worked developing with OpenGL, SDL, Box2D, Bullet, Recast and developed games with it (listed below)
  
# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Gaming
   - Motorcycles
   - Sports
   - Travelling

#(https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
